### ISSUE TITLE
Improve Development Experience with Docker

### ISSUE THREAD

**Issue by brady-vitrano** [rackerlabs/zoolander#19]
Add Docker containers and scripts for development, CI, and Test environments.

-----
**TODO**
- [x] Create Dockerfile (see below)
- [x] Remove `bundle install` from `package.json` `postinstall` or make it optional for compatibility with Docker build container
- [ ] ~~Create Docker Container hosted on public Docker Hub using Dockerfile (one less step for devs)~~ Removed until investigation of shared RAX account.
- [x] Fix `Gemfile.lock` or remove it
- [x] Update docs

-----
**Running Docs Locally**
**Note:** Remove current `Gemfile.lock`
```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 9000:4000 jekyll/jekyll jekyll serve --watch
```
-----
**Grunt/Bower Build Dockerfile** - Adapted from Jekyll Dockerfile + Grunt & Bower
**Pending:** `npm install` at run time

```
FROM envygeeks/alpine
MAINTAINER "Brady Vitrano <brady.vitrano@rackspace.com>"
RUN apk --update add build-base \
                     ruby ruby-dev ruby-io-console ruby-irb ruby-json ruby-rake ruby-rdoc \
                     nodejs \
                     && \

    mkdir -p /home/bob && \
    addgroup -Sg 1000 bob &&  \
    adduser  -SG bob -u 1000 -h /home/bob bob && \
    chown bob:bob /home/bob && \

    cd ~ && \
    yes | gem update --system --no-document -- --use-system-libraries && \
    yes | gem update --no-document -- --use-system-libraries && \

    cd ~ && \
    gem install sass --no-document && \

    npm install -g bower grunt-cli && \
    echo '{ "allow_root": true }' > /root/.bowerrc && \
    gem clean && \
    apk del build-base ruby-rdoc ruby-dev && \

    mkdir -p /src/app && \
    chown bob:bob /src/app && \
    echo 'bob ALL=NOPASSWD:ALL' >> /etc/sudoers && \
    rm -rf /usr/lib/ruby/gems/*/cache/*.gem && \
    rm -rf /var/cache/apk/* && \
    docker-helper cleanup

WORKDIR /src/app
```

**Comment by SyntaxStacks** [comment]
Wrap the docker command in `package.json` under scripts. That will help make it easier for developers to consume.

**Comment by brady-vitrano** [comment]
@SyntaxStacks that is the goal by end of this PR. It should have simple commands to fire up the containers for dev, test, and CI.

**Comment by SyntaxStacks** [comment]
Nice. I chimed in because I didn't see it in the checklist.

**Comment by brady-vitrano** [comment]
For developer environment, developers will run `docker-compose up -d` which will create required `watch` services for both Docs and Grunt tasks in detached mode (optional of course).

@SyntaxStacks here is the suggested workflow for developers to manage the containers.

```
docker-compose up -d
docker-compose ps # verify services are running and get mapped ports
docker-compose logs # get logs, if needed
docker-compose start | stop | restart | etc
```
